### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by cyber01**
Hi, I did a Russian translation for the mod. I also plan to support it in future updates.

### CODE REVIEW

**Comment by NicJames2378** [comment]
Thank you! I'll get it merged and updated on CurseForge in about 6 hours or so when I get home to my PC. I appreciate your work on this!

**Comment by cyber01** [comment]
:)
What about tree/lepid support?

**Comment by NicJames2378** [comment]
It's something I'd thought about adding, but I've never bred the
butterflies or trees so I'd have to look into how they work.

>

**Comment by NicJames2378** [comment]
Uploading version with translation to CurseForge now. Sorry for the delay! If you could, open an issue for each of those things you mentioned? Helps me keep up with what needs worked on (and you opening the issue reminds me who to credit lol).

**Pull request merged**
